### ISSUE TITLE
Estonian verb subject gets dropped when Sno is imported

### ISSUE THREAD

**Issue by kristiank** [kristiank/GF-midwife#1]
All works when only Estonian language is imported
```shell
> i MidwifeEst.gf
> Midwife
> p "patsient tunneb hästi looteliigutusi"
FeelsFetalMovements Strong
```

But after importing Snomedish it works, but the somehow parser fails
```shell
> i MidwifeSno.gf
> p "patsient tunneb hästi looteliigutusi"
FeelsFetalMovements Strong

The parser failed at token 1: "patsient"
```

All still works, but I can't understand why the parser fails. Before restarting the gf environment and re-importing the grammars for writing this issue, then the subject (_patsient_) simply vanished and I could only parse "tunneb hästi looteliigutusi".

**Comment by kristiank** [comment]
Relevant code and pointers:

The Estonian linearization puts in the "default" subject.
https://github.com/kristiank/GF-midwife/blob/e7a0dbc50d3415f05aa5bc21661eadc83e05730f/MidwifeEst.gf#L48

Whereas the Snomed linearization only puts the `level`-record
https://github.com/kristiank/GF-midwife/blob/e7a0dbc50d3415f05aa5bc21661eadc83e05730f/MidwifeSno.gf#L41
which is simply
https://github.com/kristiank/GF-midwife/blob/e7a0dbc50d3415f05aa5bc21661eadc83e05730f/MidwifeSno.gf#L42

**Comment by inariksit** [comment]
> All still works, but I can't understand why the parser fails. Before restarting the gf environment and re-importing the grammars for writing this issue, then the subject (patsient) simply vanished and I could only parse "tunneb hästi looteliigutusi".

Not sure what you mean. If we look at the output (annotations mine):

```haskell
> p "patsient tunneb hästi looteliigutusi"
FeelsFetalMovements Strong   -- This is the correct parse from MidwifeEst

The parser failed at token 1: "patsient" -- This is the output from trying to parse the sentence in MidwifeSno
```

If you have all languages imported, and only want to parse in one, you can add the `-lang=Est` flag in the command, like this:

```
Midwife> p -lang=Est "patsient tunneb hästi looteliigutusi"
FeelsFetalMovements Strong
```

**Comment by kristiank** [comment]
> If you have all languages imported, and only want to parse in one, you can add the `-lang=` flag in the command

Okay, this explains it. I guess it would have been more self-evident for me, if the fault message in the output would somehow be marked by language.

Thank you very much!
